# Generated by Django 3.2.5 on 2021-07-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('allows_free_cancellation', models.BooleanField(blank=True, default=False)),
                ('allows_pay_at_stay', models.BooleanField(blank=True, default=False)),
                ('allows_special_offers', models.BooleanField(blank=True, default=False)),
                ('has_free_wifi', models.BooleanField(blank=True, default=False)),
                ('has_free_parking', models.BooleanField(blank=True, default=False)),
                ('has_restaurant', models.BooleanField(blank=True, default=False)),
                ('has_pool', models.BooleanField(blank=True, default=False)),
                ('has_ac', models.BooleanField(blank=True, default=False)),
                ('price', models.FloatField()),
                ('total_ratings', models.PositiveIntegerField()),
                ('average_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=63)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('is_vacant', models.BooleanField(blank=True, default=True)),
                ('booked', models.DateField(blank=True, default=None, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place'),
        ),
    ]
