# Generated by Django 3.2.5 on 2021-07-27 09:54

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210727_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('allows_free_cancellation', models.BooleanField(blank=True, default=False)),
                ('allows_special_offers', models.BooleanField(blank=True, default=False)),
                ('has_free_wifi', models.BooleanField(blank=True, default=False)),
                ('has_free_parking', models.BooleanField(blank=True, default=False)),
                ('price', models.CharField(blank=True, choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=7)),
                ('total_ratings', models.PositiveIntegerField(blank=True, default=0)),
                ('average_rating', models.FloatField(blank=True, default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to)),
                ('link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=63, null=True)),
                ('has_bengali', models.BooleanField(blank=True, default=False)),
                ('has_international', models.BooleanField(blank=True, default=False)),
                ('has_indian', models.BooleanField(blank=True, default=False)),
                ('has_thai', models.BooleanField(blank=True, default=False)),
                ('has_chinese', models.BooleanField(blank=True, default=False)),
                ('has_mexican', models.BooleanField(blank=True, default=False)),
                ('has_italian', models.BooleanField(blank=True, default=False)),
                ('has_korean', models.BooleanField(blank=True, default=False)),
                ('has_bar', models.BooleanField(blank=True, default=False)),
                ('has_fast_food', models.BooleanField(blank=True, default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
    ]
